#ifndef ECU_TRAFFIC_PROFILE_H
#define ECU_TRAFFIC_PROFILE_H

/*
 * M10只用编译期常量选择确定性流量档位。每个Keil target必须显式定义
 * ECU_TRAFFIC_PROFILE，避免运行中切档或由主机sleep估算物理速率。
 */
#define ECU_TRAFFIC_PROFILE_111   111U
#define ECU_TRAFFIC_PROFILE_500   500U
#define ECU_TRAFFIC_PROFILE_1000 1000U

#ifndef ECU_TRAFFIC_PROFILE
#define ECU_TRAFFIC_PROFILE ECU_TRAFFIC_PROFILE_111
#endif

#if (ECU_TRAFFIC_PROFILE != ECU_TRAFFIC_PROFILE_111) && \
    (ECU_TRAFFIC_PROFILE != ECU_TRAFFIC_PROFILE_500) && \
    (ECU_TRAFFIC_PROFILE != ECU_TRAFFIC_PROFILE_1000)
#error "ECU_TRAFFIC_PROFILE must be 111, 500, or 1000"
#endif

/*
 * 压力档使用100-slot超帧：90个0x100、9个0x101和1个0x102。
 * 500档每2 ms一个slot，1000档每1 ms一个slot，得到精确整数速率。
 */
#define ECU_STRESS_SUPERFRAME_SLOTS 100U

#if ECU_TRAFFIC_PROFILE == ECU_TRAFFIC_PROFILE_500
#define ECU_STRESS_SLOT_PERIOD_MS 2U
#elif ECU_TRAFFIC_PROFILE == ECU_TRAFFIC_PROFILE_1000
#define ECU_STRESS_SLOT_PERIOD_MS 1U
#endif

#endif
