#ifndef GATEWAY_VEHICLE_PROTOCOL_H
#define GATEWAY_VEHICLE_PROTOCOL_H

enum {
    GATEWAY_CAN_ID_VEHICLE_DYNAMICS = 0x100,
    GATEWAY_CAN_ID_POWER_STATUS = 0x101,
    GATEWAY_CAN_ID_BODY_STATUS = 0x102,
    GATEWAY_CAN_TARGET_ID_COUNT = 3
};

#endif
